apiVersion: batch/v1
kind: Job
metadata:
  name: kafka-producer
  namespace: bigdata
spec:
  backoffLimit: 3
  template:
    metadata:
      labels:
        app: kafka-producer
    spec:
      restartPolicy: OnFailure

      initContainers:
        - name: wait-for-kafka
          image: confluentinc/cp-kafka:7.5.1
          command:
            - sh
            - -c
            - |
              echo "Waiting for Kafka..."
              until kafka-broker-api-versions --bootstrap-server kafka:9092 >/dev/null 2>&1; do
                sleep 5
              done
              echo "Kafka ready"

        - name: load-csv
          image: busybox:1.36
          command:
            - sh
            - -c
            - |
              if [ -f /data/flights.csv ]; then
                echo "CSV already exists, skipping download"
              else
                echo "Copying CSV..."
                cp /source/flights.csv /data/flights.csv
                chmod 644 /data/flights.csv
              fi
          volumeMounts:
            - name: csv-data
              mountPath: /data
            - name: csv-source
              mountPath: /source

      containers:
        - name: producer
          image: python:3.10-slim
          workingDir: /app
          env:
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: kafka:9092
            - name: KAFKA_TOPIC
              value: flights_topic
            - name: CSV_FILE
              value: /data/flights.csv
          command:
            - sh
            - -c
            - |
              pip install --no-cache-dir kafka-python
              python kafka_producer.py
          volumeMounts:
            - name: csv-data
              mountPath: /data
            - name: app-code
              mountPath: /app

      volumes:
        - name: csv-data
          persistentVolumeClaim:
            claimName: csv-data
        - name: app-code
          configMap:
            name: kafka-producer-script