---
apiVersion: v1
kind: Service
metadata:
  name: datanode
  namespace: bigdata
  labels:
    app: datanode
spec:
  ports:
    - port: 9866
      protocol: TCP
      name: dn-data
    - port: 9867
      protocol: TCP
      name: dn-rpc
    - port: 9864
      protocol: TCP
      name: dn-web
  selector:
    app: datanode
  clusterIP: None
  type: ClusterIP
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: datanode
  namespace: bigdata
  labels:
    app: datanode
spec:
  serviceName: datanode
  replicas: 1
  selector:
    matchLabels:
      app: datanode
  template:
    metadata:
      labels:
        app: datanode
    spec:
      initContainers:
      - name: wait-for-namenode
        image: busybox:1.36
        command:
          - sh
          - -c
          - |
            echo "Waiting for NameNode DNS..."
            sleep 30
            for i in $(seq 1 30); do
              if nc -z namenode-0.namenode.bigdata.svc.cluster.local 8020; then
                echo "NameNode is reachable"
                exit 0
              fi
              echo "Still waiting... (tries $i/30)"
              sleep 5
            done
            echo "NameNode not reachable, restarting."
            exit 1
      containers:
      - name: datanode
        image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
        env:
        - name: CORE_CONF_fs_defaultFS
          value: hdfs://namenode-0.namenode.bigdata.svc.cluster.local:8020
        ports:
        - containerPort: 9866
          name: dn-data
        - containerPort: 9867
          name: dn-ipc
        - containerPort: 9864
          name: dn-http
        resources:
          limits:
            cpu: "250m"
            memory: 512Mi
        volumeMounts:
        - name: datanode-pv-claim
          mountPath: /hadoop/dfs/data
  volumeClaimTemplates:
  - metadata:
      name: datanode-pv-claim
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: namenode
  namespace: bigdata
  labels:
    app: namenode
spec:
  ports:
    - port: 8020
      protocol: TCP
      name: nn-rpc
    - port: 9870
      protocol: TCP
      name: nn-web
  selector:
    app: namenode
  type: ClusterIP
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: namenode
  namespace: bigdata
  labels:
    app: namenode
spec:
  serviceName: namenode
  replicas: 1
  selector:
    matchLabels:
      app: namenode
  template:
    metadata:
      labels:
        app: namenode
    spec:
      initContainers:
      - name: delete-lost-found
        image: busybox
        command: ["sh", "-c", "rm -rf /hadoop/dfs/name/lost+found"]
        volumeMounts:
        - name: namenode-pv-claim
          mountPath: /hadoop/dfs/name
      containers:
      - name: namenode
        image: bde2020/hadoop-namenode:2.0.0-hadoop3.2.1-java8
        env:
        - name: CLUSTER_NAME
          value: hdfs-k8s
        - name: HDFS_CONF_dfs_permissions_enabled
          value: "false"
        ports:
        - containerPort: 8020
          name: nn-rpc
        - containerPort: 9870
          name: nn-web
        resources:
          limits:
            cpu: "500m"
            memory: 256Mi
        volumeMounts:
        - name: namenode-pv-claim
          mountPath: /hadoop/dfs/name
  volumeClaimTemplates:
  - metadata:
      name: namenode-pv-claim
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 5Gi