apiVersion: v1
kind: ConfigMap
metadata:
  name: hadoop-env
  namespace: bigdata
data:
  CORE_CONF_fs_defaultFS: "hdfs://namenode:9000"
  CORE_CONF_hadoop_http_staticuser_user: "root"
  HDFS_CONF_dfs_replication: "1"
  HDFS_CONF_dfs_permissions_enabled: "false"
  HDFS_CONF_dfs_webhdfs_enabled: "true"
  HDFS_CONF_dfs_datanode_use_datanode_hostname: "false"
  HDFS_CONF_dfs_client_use_datanode_hostname: "false"
  HDFS_CONF_dfs_namenode_datanode_registration_ip___hostname___check: "false"