apiVersion: v1
kind: Service
metadata:
  name: hdfs
  namespace: bigdata
  labels:
    app: hdfs
spec:
  clusterIP: None
  selector:
    app: hdfs
  ports:
  - name: dummy
    port: 80
    targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: namenode
  namespace: bigdata
  labels:
    app: namenode
spec:
  selector:
    app: namenode
  ports:
  - name: rpc
    port: 9000
    targetPort: 9000
  - name: http
    port: 9870
    targetPort: 9870
---
apiVersion: v1
kind: Service
metadata:
  name: datanode
  namespace: bigdata
spec:
  clusterIP: None
  selector:
    app: datanode
  ports:
    - name: data
      port: 9864