apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: namenode
  namespace: bigdata
spec:
  serviceName: namenode
  replicas: 1
  selector:
    matchLabels:
      app: namenode
  template:
    metadata:
      labels:
        app: namenode
    spec:
      containers:
        - name: namenode
          image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
          command:
            - /bin/bash
            - -c
            - |
              if [ ! -d /hadoop/dfs/name/current ]; then
                hdfs namenode -format -force;
              fi
              hdfs namenode &
          ports:
            - containerPort: 9000
            - containerPort: 9870
          volumeMounts:
            - name: hdfs-config
              mountPath: /opt/hadoop/etc/hadoop
            - name: namenode-data
              mountPath: /hadoop/dfs/name
      volumes:
        - name: hdfs-config
          configMap:
            name: hdfs-config
  volumeClaimTemplates:
    - metadata:
        name: namenode-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 5Gi
