apiVersion: 1

datasources:
  - name: Cassandra
    type: hadesarchitect-cassandra-datasource
    access: proxy
    url: cassandra:9042
    isDefault: true
    editable: true
    jsonData:
      keyspace: flights_db
      user: ""
      consistency: ONE