apiVersion: v1
kind: ConfigMap
metadata:
  name: hadoop-env
  namespace: bigdata
data:
  CORE_CONF_fs_defaultFS: hdfs://namenode:9000
  HDFS_CONF_dfs_replication: "1"
  HDFS_CONF_dfs_permissions_enabled: "false"
