apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasource
  namespace: bigdata
data:
  datasource.yaml: |
    apiVersion: 1
    datasources:
      - name: Cassandra
        type: hadesarchitect-cassandra-datasource
        access: proxy
        url: cassandra.bigdata.svc.cluster.local:9042
        isDefault: true
        editable: true
        jsonData:
          consistency: ONE
          keyspace: 'flights_db'
        version: 1